## 排序搜索计数

**如何通过第n列对一个数组进行排序**

【知识点:排序】

- (提示: argsort)



In [6]:
Z = np.random.randint(0,10,(3,3))
print (Z)


[[1 6 0]
 [7 0 3]
 [0 6 0]]


In [7]:
print (Z[Z[:,2].argsort()])

[[1 6 0]
 [0 6 0]
 [7 0 3]]


**对x的列进行排序，先按照最后一行排序，假如两数相等则按照倒数第二行排序**

【知识点:排序】

- (提示: lexsort)


In [17]:
import numpy as np

x=np.array([[1,2,3,4],[1,4,3,3]])

In [18]:
y=np.lexsort(x,axis=0)
display(y)
display(x[:,y])

array([0, 2, 3, 1], dtype=int64)

array([[1, 3, 4, 2],
       [1, 3, 3, 4]])

**取出每一列比第三大的数字小的数**
【知识点：排序】
- （提示：np.argpartition/np.partition）

In [38]:
import numpy as np

np.random.seed(100)
x = np.random.randint(1, 30, [8, 3])
print(x)
# [[ 9 25  4]
#  [ 8 24 16]
#  [17 11 21]
#  [ 3 22  3]
#  [ 3 15  3]
#  [18 17 25]
#  [16  5 12]
#  [29 27 17]]



[[ 9 25  4]
 [ 8 24 16]
 [17 11 21]
 [ 3 22  3]
 [ 3 15  3]
 [18 17 25]
 [16  5 12]
 [29 27 17]]


In [39]:
z = np.argpartition(x, kth=2, axis=0)
y=np.array([[ x[z[i,j],j]for j in range(3)]for i in range(2)])
print(y)

[[ 3  5  3]
 [ 3 11  3]]


In [36]:
np.partition(x, kth=2, axis=0)[:2]

array([[ 3,  5,  3],
       [ 3, 11,  3]])

**从`arr`中提取所有奇数。**

- `arr = np.arange(10)`

【知识点：搜索】
- 如何从一维数组中提取满足指定条件的元素？

In [8]:
#【答案】
import numpy as np

arr = np.arange(10)

# 方法1
index = np.where(arr % 2 == 1)
print(arr[index])
# [1 3 5 7 9]

# 方法2
x = arr[arr % 2 == 1]
print(x)
# [1 3 5 7 9]

[1 3 5 7 9]
[1 3 5 7 9]


**将`arr`中的偶数元素替换为0。**

- `arr = np.arange(10)`

【知识点：搜索】
- 如何用numpy数组中的另一个值替换满足条件的元素项？

In [9]:
import numpy as np

arr = np.arange(10)
index = np.where(arr % 2 == 0)
arr[index] = 0
print(arr)
# [0 1 0 3 0 5 0 7 0 9]

[0 1 0 3 0 5 0 7 0 9]


**将 `arr` 中的所有偶数元素替换为0，而不改变arr。**
- `arr = np.arange(10)`

【知识点：搜索】
- 如何在不影响原始数组的情况下替换满足条件的元素项？

In [10]:
import numpy as np

arr = np.arange(10)

# 方法1
x = np.where(arr % 2 == 0, 0, arr)
print(x)
# [0 1 0 3 0 5 0 7 0 9]
print(arr)
# [0 1 2 3 4 5 6 7 8 9]

# 方法2
x = np.copy(arr)
x[x % 2 == 0] = 0
print(x)
# [0 1 0 3 0 5 0 7 0 9]
print(arr)
# [0 1 2 3 4 5 6 7 8 9]

[0 1 0 3 0 5 0 7 0 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 0 3 0 5 0 7 0 9]
[0 1 2 3 4 5 6 7 8 9]


**获取给定数组a中前5个最大值的位置。**

- `a = np.random.uniform(1, 50, 20)`

【知识点：搜索】
- 如何从numpy数组中获取最大的n个值的位置？

In [11]:
import numpy as np

np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)
# [27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
#  33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
#  10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
#  40.99501269 14.42961361]

# 方法1
b = np.argsort(a)
print(b)
print(b[-5:])
# [18  7  3 10 15]

# 方法2
b = np.sort(a)
b = np.where(a >= b[-5])
print(b)
# (array([ 3,  7, 10, 15, 18], dtype=int64),)

# 方法3
b = np.argpartition(a, kth=-5)
print(b[-5:])
# [18  7  3 10 15]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]
[18  7  3 10 15]
(array([ 3,  7, 10, 15, 18], dtype=int64),)
[18  7  3 10 15]


**删除一维numpy数组中所有NaN值。**

- `a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])`

【知识点：逻辑函数、搜索】
- 如何删除numpy数组中的缺失值？

In [12]:
import numpy as np

a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
b = np.isnan(a)
c = np.where(np.logical_not(b))
print(a[c])
# [1. 2. 3. 5. 6. 7.]

[1. 2. 3. 5. 6. 7.]


**获取给定数组a中比7大的数有多少。**

- `a = np.random.uniform(1, 50, 20)`

【知识点：搜索】


In [47]:
a=np.random.uniform(1, 50, 10)
print(a)
len(a)-np.searchsorted(a,7,side='right')

[35.37289863 19.89303398  1.85370469  3.49737665 22.31851519 48.86534949
  5.59538215 28.0244556  32.512054   22.572477  ]


6

## 集合操作

**获取数组a和数组b之间的公共项。**

- `a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])`
- `b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])`

【知识点：集合操作】
- 如何获取两个numpy数组之间的公共项？

In [13]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
x = np.intersect1d(a, b)
print(x)  # [2 4]

[2 4]


**从数组a中删除数组b中的所有项。**
- `a = np.array([1, 2, 3, 4, 5])`
- `b = np.array([5, 6, 7, 8, 9])`

【知识点：集合操作】
- 如何从一个数组中删除存在于另一个数组中的项？

In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
x = np.setdiff1d(a, b)
print(x)  # [1 2 3 4]

[1 2 3 4]
