**创建一个形为5×3的二维数组，以包含5到10之间的随机数。**

【知识点：随机抽样】
- 如何创建随机二维数组？

In [1]:
import numpy as np

x = np.random.randint(5, 10, [5, 3])
print(x)
# [[5 8 8]
#  [5 6 8]
#  [8 8 7]
#  [6 7 9]
#  [6 5 8]]

x = np.random.uniform(5, 10, [5, 3])
print(x)
# [[6.73675226 8.50271284 9.66526032]
#  [9.42365472 7.56513263 7.86171898]
#  [9.31718935 5.71579324 9.92067933]
#  [8.90907128 8.05704153 6.0189007 ]
#  [8.70753644 7.75056151 5.71714203]]

[[6 7 6]
 [5 6 5]
 [8 8 8]
 [9 8 7]
 [8 7 6]]
[[7.17742843 9.67201535 6.03259923]
 [9.67097091 9.08662124 5.13643319]
 [7.51864734 7.7036486  7.8195777 ]
 [5.50024593 9.66330664 5.18939603]
 [8.34728051 5.3017636  6.30038456]]
