**将 `arr`转换为2行的2维数组。**
- `arr = np.arange(10)`

【知识点：数组的操作】
- 如何改变数组的形状？

In [1]:
import numpy as np

arr = np.arange(10)

# 方法1
x = np.reshape(arr, newshape=[2, 5])
print(x)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

# 方法2
x = np.reshape(arr, newshape=[2, -1])
print(x)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


**垂直堆叠数组a和数组b。**
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

【知识点：数组操作】
- 如何垂直叠加两个数组？

In [2]:
import numpy as np

a = np.arange(10).reshape([2, -1])
b = np.repeat(1, 10).reshape([2, -1])

print(a)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
print(b)
# [[1 1 1 1 1]
#  [1 1 1 1 1]]

# 方法1
print(np.concatenate([a, b], axis=0))
# [[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

# 方法2
print(np.vstack([a, b]))
# [[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**8. 将数组a与数组b水平堆叠。**
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

【知识点：数组的操作】
- 如何水平叠加两个数组？

In [3]:
import numpy as np

a = np.arange(10).reshape([2, -1])
b = np.repeat(1, 10).reshape([2, -1])

print(a)
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
print(b)
# [[1 1 1 1 1]
#  [1 1 1 1 1]]

# 方法1
print(np.concatenate([a, b], axis=1))
# [[0 1 2 3 4 1 1 1 1 1]
#  [5 6 7 8 9 1 1 1 1 1]]

# 方法2
print(np.hstack([a, b]))
# [[0 1 2 3 4 1 1 1 1 1]
#  [5 6 7 8 9 1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**将 `arr`的2维数组按列输出。**
- `arr =  np.array([[16, 17, 18, 19, 20],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[26, 27, 28, 29, 30]])`

【知识点：数组的操作】
- 如何访问二维数组的全部元素，并按列输出？

In [5]:
import numpy as np
arr =  np.array([[16, 17, 18, 19, 20],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[26, 27, 28, 29, 30]])
y = arr.flatten(order='F')
print(y)

[16 11 21 31 26 17 12 22 32 27 18 13 23 33 28 19 14 24 34 29 20 15 25 35
 30]


**给定两个随机数组A和B，验证它们是否相等。**

- `A = np.random.randint(0,2,5) B = np.random.randint(0,2,5)`

In [6]:
import numpy as np
A = np.array([1,2,3])
B = np.array([1,2,3])

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

True
True


**在给定的numpy数组中找到重复的条目（第二次出现以后），并将它们标记为True。第一次出现应为False。**

- `a = np.random.randint(0, 5, 10)`

【知识点：数组操作】
- 如何在numpy数组中找到重复值？

In [6]:
import numpy as np

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
# [0 0 3 0 2 4 2 2 2 2]
b = np.full(10, True)
vals, counts = np.unique(a, return_index=True)
b[counts] = False
print(b)
# [False  True False  True False False  True  True  True  True]

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


**建立一个随机数在1-10之间的3行2列的数组，并将其转换成2行3列的数组。**

【知识点：数组的操作】
- 改变数组形状？

In [4]:
import numpy as np
x = np.random.randint(10, size=[3, 2])
print(x)
y = np.reshape(x, [2,3])
print(y)

[[9 0]
 [3 3]
 [4 6]]
[[9 0 3]
 [3 4 6]]
